### ISSUE TITLE
label:question can I install AQ on Linux? 

### ISSUE THREAD

**Issue by magic-space** [ArchaicQuest/ArchaicQuest-II#19]
Hi visualstudio I have been installed.

So all what I see on your docu is for windows.

Can you a me a give me a little bit support zu make this?

Love greetings from Germany

**Comment by LiamKenneth** [comment]
Hey, you need dotnet core 3.1 installed https://docs.microsoft.com/en-us/dotnet/core/install/linux

once installed you can use the make file at the project root to build the project and run.

this is the file https://github.com/ArchaicQuest/ArchaicQuest-II/blob/master/Makefile

in a command prompt enter `make run` to start the project.

To add content to the game and to connect with the web client you'll need these projects:
https://github.com/ArchaicQuest/ArchaicQuest-II-Web-Admin
https://github.com/ArchaicQuest/ArchaicQuest-II-Web-Client

^these 2 are angular projects so need node installed and just run `npm install` and then `npm start`

let me know if you have more questions

**Comment by magic-space** [comment]
Wow mega thanks to you I will check that out.

**Comment by magic-space** [comment]
When I make this I can't connect to the admin panel ore web client. I follow your tutorial.

I will check your docs. 

Ore you have an answer for me. 

When I start the server this tells me loop

**Comment by magic-space** [comment]
Now I installed mongo db to are for version 2 I can't find docu

**Comment by LiamKenneth** [comment]
You don't need MongoDB, the database is Lite db and part of the project.

in the folder you have AQ downloaded run this in the console `dotnet run -p ArchaicQuestII.API/ArchaicQuestII.API.csproj`
in the console it will say it's running on localhost:xxx if successful.

also make sure dotnet is a recognized command and installed properly.

What trouble are you having with the admin project? It will only work if the AQ server is running

**Comment by magic-space** [comment]
Now clone AQ2 and CD in project root AQ2 than command make.
After this when is finished with no errors I command this make run. 

Server successfully startet with port when I go to my browser and I'm add the ip + port in terminal se the connection. I know here on the server side I can't see anymore.

Next I installed AQ2Admin in terminal I command this cd .. /
