### ISSUE TITLE
Add Money to the game.

### ISSUE THREAD

**Issue by LiamKenneth** [ArchaicQuest/ArchaicQuest-II#22]
### **In the Item class (found in the Item folder of the GameLogic project)** 

1. Add a new enum value to ItemTypes called Money
2. Add a property of type int called Value to Item.cs this is to store the value of the money.

### With a money item in the room, assuming it's called Gold coin

1. The user will see "(500) gold coins stacked here." 
   - 500 comes from the value property of the item.
2. If there is more than one the user will see
   - "(500) gold coins stacked here." 
   - "(250) gold coins stacked here." 
   - "(1) gold coin here." 
3. If there is only 1 coin it should display
    - "(1) gold coin here." and not "(1) gold coins stacked here." 
 
### When a user picks up the item, it should not be visible in it's inventory 
1. In the inventory class (found in the commands folder of the GameLogic project) On the foreach of `player.Inventory` and a query to get all items where type != money

### When a user picks up the item, the value needs to be added to the player
 1. In the Object class (found in the commands folder of the GameLogic project)
   **in these methods:**
     - Get
	- GetAll
	- GetAllContainer
	- GetFromContainer
	
2. when the item is type money, add the value to player.Money.Value but don't save the item to the inventory.
	
### When a user drops money, the value needs to be deducted from the player
1. In the Object class (found in the commands folder of the GameLogic project)
   **in these methods:**
    - Drop
	- DropAll
	- DropAllContainer
	- DropInContainer
	
This will need to generate a new Money item for the room, probably in the Object class create a GenerateCoin method that takes a int value as a prameter and generates the correct room descriptions based on the value.

**Comment by dmbyer** [comment]
Should UpdateClientUI.UpdateInventory also not list the money? Or where is the money total being shown to the player?

**Comment by LiamKenneth** [comment]
It's shown in score but looking at it, it's not clear. So probably it should appear in inventory. That also makes sense for transferring gold to containers to keep them safe.
