### ISSUE TITLE
UI Notice: HP and other bars are distractingly large and kind of annoying.

### ISSUE THREAD

**Issue by BoQsc** [ArchaicQuest/ArchaicQuest-II#36]
I'm not sure how to make it look better right now. I just noticed this being a problem.

![image](https://user-images.githubusercontent.com/21064622/126611895-93714f3c-5550-419f-9b40-2417e0d04800.png)

I think at the very least: 
* The bars could be placed horizontally and made smaller somewhere.

![image](https://user-images.githubusercontent.com/21064622/126612316-bfcbc3f7-3477-4252-be54-c415759aaa68.png)

Also: 
* **darker colors** would be **better for those bars**, 
   * maybe adding some darker texture to them would help out as well. 

**Personally the bars are too complex.** 
* I'd remove this one from the whole game, whatever that is:
  ![image](https://user-images.githubusercontent.com/21064622/126613078-28e6a79e-ffa0-4a09-bf90-3cee0572fe8a.png)

**And remember to label what each bar does:**
![image](https://user-images.githubusercontent.com/21064622/126613542-b49a7873-ceb1-4a0f-a4cb-083e6d63dcde.png)

I'm completely lazy today.

Larger interface
![image](https://user-images.githubusercontent.com/21064622/126613838-48511ada-039b-47b8-9bd8-afab564a7bbe.png)
Smaller interface
![image](https://user-images.githubusercontent.com/21064622/126614283-759aa5e0-61fd-4752-8fd3-fa275d393b07.png)

**Comment by LiamKenneth** [comment]
Thanks for this, I've had other comments about the bars and the use of space. It makes sense to have multiple themes so everyone can pick based on taste. Looks like you hit the old site though, the V2 version is found here: [https://play.archaicquest.com](https://play.archaicquest.com)

![ui](https://user-images.githubusercontent.com/9481725/126652478-4d9c3bb8-4222-4b72-a130-d9825ec7f875.jpg)
This is the v2 UI, still suffers from the bars and the lack of description of what they are!

I like where you have placed the bars on the left, I can definitely remove the top widget as you don't need to stare at your stats the whole time so the widget below can move up and the score tab can be incorporated there. then plenty of room for the stat bars.

in v2 I haven't added the predefined command buttons, unsure if it's helpful or annoying, it's probably better for mobile and to be togglable.

100% agree on autocomplete would be a nice touch, in v2 though you can click on items and be given a modal with options like look, get. needs to be extended to mobs too

**Comment by BoQsc** [comment]
> Looks like you hit the old site though,

Yeah, I did and it feels more warm and medieval style gives out some charm. 
The old site style could include some UI fixes from the V2 version and it would be perfect.

> in v2 I haven't added the predefined command buttons, **unsure if it's helpful or annoying**, it's probably better for mobile and to be togglable.

They are well fit once these huge RED BLUE GREE and VIOLET bars are re-moved.  
I think they (the buttons) are helpful and makes the gameplay more smooth, kind of resembles 
a suggestion for action.
