### ISSUE TITLE
Potential Memory Leak

### ISSUE THREAD

**Issue by AriesNinjaDev** [ArchaicQuest/ArchaicQuest-II#74]
I was attempting to run Archaic on 3 Repl.it projects, but the memory useage for building the client went up way too high and didn't work. Is there already a fix for this?

**Comment by DrunkenImpGameStudio** [comment]
Do you have any logs, or additional info? Clean build?

**Comment by LiamKenneth** [comment]
Hey I had a look, you don't start with much free memory and you have to run 2 projects to get it to work locally.  

With just a simple hello world app you're almost using half the allocated ram

The .net project runs fine but even running the build for that exceeds the 512mb memory limit.  With the web client I was hitting over 900mb with the .net project running and obviously the client build process gets killed. 

To be honest there is nothing we can do to solve that, the client build is part of angular which uses webpack and is known to be a memory hog.  Best to run it locally but if you can't you will need to use a service that gives you at least 1.5gb of ram

![image](https://user-images.githubusercontent.com/9481725/213428848-56befc0d-8a12-4f98-8d12-bfeb09285340.png)

![image](https://user-images.githubusercontent.com/9481725/213431218-4433deed-6630-43f8-b42f-7f53a1a14c65.png)
